import { mkdir } from "node:fs/promises";
import { join } from "node:path";
import { appendUnique, writeTemplate } from "@/cli/utils/files";
import { camelCase, pascalCase } from "@/cli/utils/string";

export async function makeApp(name: string) {
  if (!name) throw new Error("Usage: npm run make:app <name>");

  const appName = name.toLowerCase();
  const appConst = `${camelCase(appName)}App`;
  const label = pascalCase(appName);
  const base = join(process.cwd(), "src/apps", appName);
  const folders = ["controllers", "services", "repositories", "routes", "validators", "schemas", "types", "tests", "migrations", "ui", "pages"];

  await Promise.all(folders.map((folder) => mkdir(join(base, folder), { recursive: true })));
  await writeTemplate(
    join(base, "index.ts"),
    `export const {{appConst}} = {
  name: "{{appName}}",
  label: "{{label}}",
  permissions: ["{{appName}}.read", "{{appName}}.write"]
} as const;
`,
    { appName, appConst, label }
  );
  await writeTemplate(
    join(base, "README.md"),
    `# {{label}} App

Generated by velajs.
`,
    { label }
  );
  await appendUnique(join(process.cwd(), "src/apps/index.ts"), `export * from "@/apps/${appName}";`);

  console.log(`Created app: ${appName}`);
}
